### ISSUE TITLE
请问你是如何判断距离的？

### ISSUE THREAD

**Issue by bxjxxyy** [GrayTempest-400/warthunder-cv2#2]
用测距仪测距等待几秒得到结果，然后识别得到距离。除了这种方法之外，是如何根据图像来判断识别到的目标的距离的？

**Comment by GrayTempest-400** [comment]
根据黄点标记和地图测距，项目是抄https://github.com/Yonisen/WarThunder_Yellow_Mark_Rangefinder的

**Comment by GrayTempest-400** [comment]
https://github.com/Yonisen/WarThunder_Yellow_Mark_Rangefinder

**Comment by GrayTempest-400** [comment]
不过我这程序还没写完，测距这部分我打算写在自动战斗中，现在还在写
