### ISSUE TITLE
考虑一下使用寻路算法，而不是使用完全的图像识别进行寻路

### ISSUE THREAD

**Issue by zaixia108** [GrayTempest-400/warthunder-cv2#4]
考虑一下处理地图细节，标记障碍后通过寻路算法实现自动寻路，我尝试过自己优化JPS寻路，实时导航延迟在200毫秒左右

**Comment by GrayTempest-400** [comment]
收到，感谢您的建议，我之前的思路经过测试并不适合自动寻路，我马上根据您的思路改

**Comment by GrayTempest-400** [comment]
您好，您是怎么实现这一过程的？我想借鉴一下您的思路，是基于地图的2d寻路还是直接3d寻路

**Comment by zaixia108** [comment]
是基于地图的2d寻路，从网页获取到精确地图后，对地图进行处理，要么人工精确处理，要么程序处理，标记障碍后，通过寻路算法实现自动导航

**Comment by GrayTempest-400** [comment]
这个我之前就试过了，我失败在没办法获取坦克箭头指向的角度，但我的合作伙伴把找箭头的模型训练出来了，在github仓库里

**Comment by GrayTempest-400** [comment]
你说的寻路算法我已经测试好放在github仓库了，我也准备把算法和游戏进行实时对接，能知道该怎么开的路线，但我没办法获得坦克行走方向，这一想法我也就无法实现

**Comment by GrayTempest-400** [comment]
能加个QQ细聊吗，我的QQ号是3462923564

**Comment by GrayTempest-400** [comment]
我现在在想办法获得坦克行走方向

**Comment by zaixia108** [comment]
加个QQ

**Comment by GrayTempest-400** [comment]
我的QQ:3462923564

**Comment by mhmh1919** [comment]
战雷这b图处理不了一点，8111上的地图就是模糊的，还有好多小障碍物根本没有标注，基本上除了大平原以外的地图都得手画

**Comment by GrayTempest-400** [comment]
是这样的，这b地图，但可以自己从游戏中记录x,y搞成自己的寻路点
