### ISSUE TITLE
更详细的说明

### ISSUE THREAD

**Issue by ss8688** [GrayTempest-400/warthunder-cv2#7]
看了2.0版，整了半天都不知道怎么用……希望说明能详细一点

**Comment by ss8688** [comment]
比如游戏分辨率

**Comment by ss8688** [comment]
界面比例

**Comment by GrayTempest-400** [comment]
行

**Comment by GrayTempest-400** [comment]
我马上出演示视频

**Comment by ss8688** [comment]
视频最好油管也发一份，b站太容易被删了

**Comment by GrayTempest-400** [comment]
https://www.bilibili.com/video/BV11P411p7yh/

**Comment by GrayTempest-400** [comment]
看readme就行，改完了

**Comment by ss8688** [comment]
还有需要的依赖也写一下，写在requirements.txt里。一个一个装容易漏装，我好像装少了什么依赖。

**Comment by ss8688** [comment]
<img width="774" alt="image" src="https://github.com/GrayTempest-400/warthunder-cv2/assets/59367202/41d86a54-b0ed-4bfb-80c3-4e781759a149">
这应该是少依赖了吧？

**Comment by GrayTempest-400** [comment]
我exe文件出了，用exe运行试试？

**Comment by ss8688** [comment]
exe直接无法运行
<img width="542" alt="image" src="https://github.com/GrayTempest-400/warthunder-cv2/assets/59367202/4033bc2d-7510-4606-8068-6f7525d3f1dc">

**Comment by ss8688** [comment]
弄好了，原来需要放到文件夹下，我以为是独立的exe

**Comment by ss8688** [comment]
exe还是不要隐藏命令行窗口好，不然出了问题什么都不知道

**Comment by GrayTempest-400** [comment]
行

**Comment by GrayTempest-400** [comment]
更了

**Comment by fankuanhui** [comment]
> 我exe文件出了，用exe运行试试？
大哥 咋找不到exe文件
